version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: pg_catalogo
    environment:
      POSTGRES_DB: catalogoDb
      POSTGRES_USER: catalogoUser
      POSTGRES_PASSWORD: catalogoPass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
